[versions]
kotlin                 = "2.0.20"
intellij-platform      = "2.5.0"
kotlinx-serialization-json = "1.8.1"
junit                  = "5.10.2"

[plugins]
kotlin                 = { id = "org.jetbrains.kotlin.jvm",                 version.ref = "kotlin" }
kotlinSerialization    = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
intelliJPlatform       = { id = "org.jetbrains.intellij.platform",          version.ref = "intellij-platform" }

[libraries]
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
junit                      = { group = "org.junit.jupiter",    name = "junit-jupiter",               version.ref = "junit" }
