# Generated by AI Agent Team Builder
from crewai import Agent, Crew, Process, Task

# Define agents
team_lead_1 = Agent(
    role="Team Lead",
    goal="Coordinate the team and ensure the project is completed successfully",
    backstory="You are a Team Lead responsible for coordinating the team and ensuring the project is completed successfully.",
    verbose=True,
    allow_delegation=True
)

engineer_1 = Agent(
    role="Software Engineer",
    goal="Implement technical solutions",
    backstory="You are a Software Engineer responsible for implementing the technical solutions.",
    verbose=True,
    allow_delegation=False
)

engineer_2 = Agent(
    role="Software Engineer",
    goal="Implement technical solutions",
    backstory="You are a Software Engineer responsible for implementing the technical solutions.",
    verbose=True,
    allow_delegation=False
)

qa_engineer_1 = Agent(
    role="QA Engineer",
    goal="Test and ensure the quality of the software",
    backstory="You are a QA Engineer responsible for testing and ensuring the quality of the software.",
    verbose=True,
    allow_delegation=False
)

# Define tasks
task = Task(
    description="Write TicTacToe game",
    expected_output="Completed implementation of the required functionality",
    agent=team_lead_1 if 1 > 0 else (tech_lead_1 if 0 > 0 else engineer_1)
)

# Define crew
agents = [
    team_lead_1,
    engineer_1,
    engineer_2,
    qa_engineer_1,
]

crew = Crew(
    agents=agents,
    tasks=[task],
    process=Process.sequential,
    verbose=True
)

# Run the crew
result = crew.kickoff()
print(result)